// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protobuf/pbMessage.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	src/protobuf/pbMessage.proto

It has these top-level messages:
	Person
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Year        int32  `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month       string `protobuf:"bytes,2,opt,name=month" json:"month,omitempty"`
	Day         int32  `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
	FullName    string `protobuf:"bytes,4,opt,name=fullName" json:"fullName,omitempty"`
	FirstName   string `protobuf:"bytes,5,opt,name=firstName" json:"firstName,omitempty"`
	LastName    string `protobuf:"bytes,6,opt,name=lastName" json:"lastName,omitempty"`
	Dob         string `protobuf:"bytes,7,opt,name=dob" json:"dob,omitempty"`
	Country     string `protobuf:"bytes,8,opt,name=country" json:"country,omitempty"`
	Description string `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
	Weekday     string `protobuf:"bytes,10,opt,name=weekday" json:"weekday,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Person) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *Person) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Person) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Person) GetWeekday() string {
	if m != nil {
		return m.Weekday
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "protobuf.Person")
}

func init() { proto.RegisterFile("src/protobuf/pbMessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0xc3, 0xee, 0xc2, 0xc2, 0x78, 0x31, 0x13, 0x0f, 0x13, 0xb3, 0x07, 0xe2, 0x69, 0x4f,
	0x72, 0xf0, 0x39, 0x34, 0x86, 0x37, 0x68, 0x61, 0x50, 0x22, 0xb4, 0xa4, 0x2d, 0x31, 0x5c, 0x7d,
	0x72, 0xd3, 0x01, 0x74, 0x6f, 0xff, 0xff, 0x7d, 0xf3, 0x07, 0x52, 0xb8, 0x78, 0xd7, 0x54, 0x93,
	0xb3, 0xc1, 0xea, 0xb9, 0xab, 0x26, 0xfd, 0xca, 0xde, 0xab, 0x0f, 0x7e, 0x16, 0x84, 0xf9, 0x6e,
	0x9e, 0x7e, 0x0e, 0x90, 0xbd, 0xb3, 0xf3, 0xd6, 0x20, 0xc2, 0x69, 0x61, 0xe5, 0x28, 0x29, 0x93,
	0x6b, 0x5a, 0x4b, 0xc6, 0x07, 0x48, 0x47, 0x6b, 0xc2, 0x27, 0x1d, 0xca, 0xe4, 0x5a, 0xd4, 0x6b,
	0xc1, 0x7b, 0x38, 0xb6, 0x6a, 0xa1, 0xa3, 0x1c, 0xc6, 0x88, 0x8f, 0x90, 0x77, 0xf3, 0x30, 0xbc,
	0xa9, 0x91, 0xe9, 0x24, 0xa7, 0x7f, 0x1d, 0x2f, 0x50, 0x74, 0xbd, 0xf3, 0x41, 0x64, 0x2a, 0xf2,
	0x1f, 0xc4, 0xe5, 0xa0, 0x36, 0x99, 0xad, 0xcb, 0xbd, 0xcb, 0x77, 0xac, 0xa6, 0xb3, 0xe0, 0x18,
	0x91, 0xe0, 0xdc, 0xd8, 0xd9, 0x04, 0xb7, 0x50, 0x2e, 0x74, 0xaf, 0x58, 0xc2, 0x5d, 0xcb, 0xbe,
	0x71, 0xfd, 0x14, 0x7a, 0x6b, 0xa8, 0x10, 0x7b, 0x8b, 0xe2, 0xf6, 0x9b, 0xf9, 0x2b, 0xfe, 0x39,
	0xac, 0xdb, 0xad, 0xea, 0x4c, 0x9e, 0xe3, 0xe5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x40, 0x14,
	0xa7, 0x35, 0x01, 0x00, 0x00,
}
